### ISSUE TITLE
Auth be broken

### ISSUE THREAD

**Issue by OscarAlvarez8830** [Eden12345/fLEXpx#1]
- [x] Logout is broken, and the button needs to be styled.
- [x] Switching between forms is a bit too slow/weird with the animation.
- [x] The animation is rendering too often. When I get errors, the animation runs again.

**Comment by Eden12345** [comment]
I removed the animations and will polish them up after I've completed the rest of my project as they are not that way in 500px (ie. not an MVP).

The logout button is styled properly now, as it is now nested within a dropdown menu like the actual 500px site. I'm having issues with the avatar picture loading, which should be fixed once I introduce paperclip attachments to my project.
